-- This script was generated by the ERD tool in pgAdmin 4.
BEGIN;

CREATE TABLE IF NOT EXISTS public."Tasks"
(
    id serial NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default" DEFAULT 'Pending'::character varying,
    "dueDate" timestamp with time zone,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    "assignedTo" integer,
    "teamId" integer,
    creator integer NOT NULL,
    CONSTRAINT "Tasks_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Teams"
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "createdBy" integer NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    "totalMembers" integer NOT NULL DEFAULT 0,
    CONSTRAINT "Teams_pkey" PRIMARY KEY (id),
    CONSTRAINT "Teams_name_key" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    id serial NOT NULL,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "refreshToken" character varying(255) COLLATE pg_catalog."default",
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    "teamId" integer,
    CONSTRAINT "Users_pkey" PRIMARY KEY (id),
    CONSTRAINT "Users_email_key" UNIQUE (email),
    CONSTRAINT "Users_refreshToken_key" UNIQUE ("refreshToken"),
    CONSTRAINT "Users_username_key" UNIQUE (username)
);

ALTER TABLE IF EXISTS public."Tasks"
    ADD CONSTRAINT "Tasks_assignedTo_fkey" FOREIGN KEY ("assignedTo")
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;

ALTER TABLE IF EXISTS public."Tasks"
    ADD CONSTRAINT "Tasks_creator_fkey" FOREIGN KEY (creator)
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public."Tasks"
    ADD CONSTRAINT "Tasks_teamId_fkey" FOREIGN KEY ("teamId")
    REFERENCES public."Teams" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;

ALTER TABLE IF EXISTS public."Teams"
    ADD CONSTRAINT "Teams_createdBy_fkey" FOREIGN KEY ("createdBy")
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public."Users"
    ADD CONSTRAINT "Users_teamId_fkey" FOREIGN KEY ("teamId")
    REFERENCES public."Teams" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;

END;
